// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rftflgwenladevqsqfxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmdGZsZ3dlbmxhZGV2cXNxZnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDcwNzAsImV4cCI6MjA2NTU4MzA3MH0.NK2E6CKfqcS2Q7uppT898Mer5wRLEOBjA34wZXpgZhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);